underline_button:
  default: "Underline"
  description:
    en: Enter the text for the title of the button in the composer.
underline_text:
  default: "Text"
  description:
    en: Enter the placeholder text that appears in the composer after the user clicks the button.
align_center_button:
  default: "Center"
  description:
    en: Enter the text for the title of the button in the composer.
align_center_text:
  default: "Text"
  description:
    en: Enter the placeholder text that appears in the composer after the user clicks the button.
align_right_button:
  default: "Align right"
  description:
    en: Enter the text for the title of the button in the composer.
align_right_text:
  default: "Text"
  description:
    en: Enter the placeholder text that appears in the composer after the user clicks the button.
align_justify_button:
  default: "Justify"
  description:
    en: Enter the text for the title of the button in the composer.
align_justify_text:
  default: "Text"
  description:
    en: Enter the placeholder text that appears in the composer after the user clicks the button.
strikethrough_button:
  default: "Strike-through"
  description:
    en: Enter the text for the title of the button in the composer.
strikethrough_prompt:
  default: "Text"
  description:
    en: Enter the placeholder text that appears in the composer after the user clicks the button.

Svg_icons: 
  type: 'list'
  list_type: 'compact'
  default: 'fa-align-center|fa-align-right|fa-align-justify|fa-strikethrough|fa-underline'
  description: 
    en: "Include FontAwesome 5 icon classes for each icon used in the list."